<?php

namespace FloarcWakeTricksBundle\Repository;

/**
 * HandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HandRepository extends \Doctrine\ORM\EntityRepository
{
}
